// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JPSOSfkjo4xY8qWUEMCFaXSFS2frOG0',
    appId: '1:1000761362671:web:47da297d43bc41a18bb31a',
    messagingSenderId: '1000761362671',
    projectId: 'essivi-drink-delivery',
    authDomain: 'essivi-drink-delivery.firebaseapp.com',
    storageBucket: 'essivi-drink-delivery.firebasestorage.app',
    measurementId: 'G-N2QVS4LCWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzGpXVvlD05dgbcw8Dm8_uRqJabaPDtcU',
    appId: '1:1000761362671:android:7454684e9b4434a08bb31a',
    messagingSenderId: '1000761362671',
    projectId: 'essivi-drink-delivery',
    storageBucket: 'essivi-drink-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-L6T01BL7uF8QX76RImYaqN40rnfmTTA',
    appId: '1:1000761362671:ios:ac06a464b35e82d58bb31a',
    messagingSenderId: '1000761362671',
    projectId: 'essivi-drink-delivery',
    storageBucket: 'essivi-drink-delivery.firebasestorage.app',
    iosBundleId: 'com.example.essiviDeliveryDrink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-L6T01BL7uF8QX76RImYaqN40rnfmTTA',
    appId: '1:1000761362671:ios:ac06a464b35e82d58bb31a',
    messagingSenderId: '1000761362671',
    projectId: 'essivi-drink-delivery',
    storageBucket: 'essivi-drink-delivery.firebasestorage.app',
    iosBundleId: 'com.example.essiviDeliveryDrink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7JPSOSfkjo4xY8qWUEMCFaXSFS2frOG0',
    appId: '1:1000761362671:web:b60c21a3fc1f6c818bb31a',
    messagingSenderId: '1000761362671',
    projectId: 'essivi-drink-delivery',
    authDomain: 'essivi-drink-delivery.firebaseapp.com',
    storageBucket: 'essivi-drink-delivery.firebasestorage.app',
    measurementId: 'G-7LXDV4N0LW',
  );
}
